version: 2.1
orbs:
  node: circleci/node@5.2.0

jobs:
  buildAndTest:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - node/install-packages
      - run: npm run build
      - run: npm run typecheck
      - run: npm run test
      - run:
          name: Upload coverage to Codacy
          command: |
            bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r coverage/lcov.info

workflows:
  version: 2
  build_and_test:
    jobs:
      - buildAndTest